import { GetStaticPaths, GetStaticProps, NextPage } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Head from "next/head";
import fs from 'fs'
import markdownToHtml from "zenn-markdown-html";
import { JSDOM } from 'jsdom'
import { useMediaQuery } from "react-responsive";
import useSize from '@react-hook/size'
import styles from '../styles/Docs.module.scss'
import { breakpointArticle, breakpointSidebar, DocsProps, TableOfContent } from "../compontents/common";
import TOC from "../compontents/TOC";
import Header from "../compontents/Header";
import { useTranslation } from "next-i18next";
import Footer from "../compontents/Footer";
import { useEffect, useRef } from "react";
import DiscordSection from "../compontents/DiscordSection";

export const getStaticProps: GetStaticProps = async ({ params, locale }) => {
  const content = fs.readFileSync(
    `content/roadmap/${locale}.md`, 'utf-8')
  const rawHtmlContent = markdownToHtml(content)
  const htmlContent = rawHtmlContent.replaceAll('<img src="', `<img src="/roadmap/`)
  const domHtml = new JSDOM(htmlContent).window.document

  const headings = domHtml.querySelectorAll<HTMLElement>("h2")
  const tableOfContent: TableOfContent[] = []
  headings.forEach((element) => {
    const level = element.tagName
    const title = element.innerHTML.split("</a> ")[1]
    const href = '#' + element.id
    tableOfContent.push({ level: level, title: title, href: href })
  })

  return {
    props: {
      ...(await serverSideTranslations(locale!, ['common'])),
      html: htmlContent,
      tableOfContent: tableOfContent
    }
  }
}

const WhatIsIt: NextPage<DocsProps> = ({ html, tableOfContent}) => {
  const { t } = useTranslation('common')
  const isLarge = useMediaQuery({
    query: `(min-width: ${breakpointSidebar}px)`
  })
  const articleRef = useRef(null)
  const [articleWidth, _] = useSize(articleRef);

  return (
    <div>
      <Head>
        <title>{`${t('roadmap')} | Zwin`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header toppage={false}/>
      <div className={styles.container}>

        <main className={styles.main}>
          <section className={styles.body}>
            {/* {isLarge && <Sidenav kind={SidenavPath.whatIsIt} />} */}
            <article className={styles.article} ref={articleRef}>
              <div className={styles.content}>
                <div className={styles.markdowninjection}
                  dangerouslySetInnerHTML={{ __html: html }}
                />
                {!isLarge && <DiscordSection alignCenter={true}/>}
              </div>
              {articleWidth > breakpointArticle && <TOC toc={tableOfContent} />}
            </article>
          </section>
        </main>
      </div>
      <Footer />
    </div>
  )
}

export default WhatIsIt
